In [3]:
import numpy as np 
import pandas as pd

from pandas_datareader import data as web
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
%matplotlib inline

import warnings
warnings.simplefilter("ignore")

numpy

In [4]:
PATH = "/home/cuneyt/Desktop/projects/python_projects/Python4Finance/"

l1 = [1, 2 ,3, 4, 5]
npa1 = np.array(l1)
print(npa1, '\n')

npa2 = np.arange(0, 5)
print(npa2, '\n')

npa3 = np.arange(0, 10, 1.5)
print(npa3, '\n')

mat1 = np.ones((4, 3))
print(mat1, '\n')

mat2 = np.zeros((4, 3))
print(mat2, '\n')

mat3 = np.random.randint(0, 10, (4, 3))
print(mat3, '\n')

mat4 = np.random.random((4, 3))
print(mat4, '\n')

[1 2 3 4 5] 

[0 1 2 3 4] 

[0.  1.5 3.  4.5 6.  7.5 9. ] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[7 1 3]
 [4 8 6]
 [3 7 3]
 [5 9 6]] 

[[0.75126468 0.98539841 0.92347426]
 [0.30611874 0.31805575 0.57517593]
 [0.18317872 0.02503202 0.4674483 ]
 [0.59544678 0.76105301 0.87341729]] 



In [5]:
mat5 = np.linspace(0, 10, 5)
print(mat5, '\n')

mat6 = np.random.randint(0, 50, 12)
print(mat6, '\n')

mat6 = mat6.reshape(4, 3)
print(mat6, '\n')

mat7 = mat6.reshape(3,4,1)
print(mat7, '\n')

print(mat7[1, 2, 0], '\n')

[ 0.   2.5  5.   7.5 10. ] 

[39 48  4 42 25 11 40 37  3 43 27 18] 

[[39 48  4]
 [42 25 11]
 [40 37  3]
 [43 27 18]] 

[[[39]
  [48]
  [ 4]
  [42]]

 [[25]
  [11]
  [40]
  [37]]

 [[ 3]
  [43]
  [27]
  [18]]] 

40 



In [6]:
print(mat6 > 20, '\n')

print(mat6[mat6>20], '\n')

mat5 = np.random.randint(0,100,50)
print(mat5, '\n')

print("Mean :", mat5.mean())
print("Standard Deviation :", mat5.std())
print("Variance :", mat5.var())
print("Min :", mat5.min())
print("Max :", mat5.max(), '\n')

np.random.seed(500)
mat9 = np.random.randint(0,50,10)
print(mat9, '\n')

mat10 = np.random.randint(0,50,10)
print(mat10, '\n')

[[ True  True False]
 [ True  True False]
 [ True  True False]
 [ True  True False]] 

[39 48 42 25 40 37 43 27] 

[40 31 42 80 37 33 49 58 18 87 89 42 54 45 82 97 21 45 11 30 66  8 48 86
 64 74 61 52 61 26 65 72 42 58 91 53 15 41 94 55 48 37 67 68 26  6 53 53
  9 33] 

Mean : 50.46
Standard Deviation : 23.651815997931322
Variance : 559.4084
Min : 6
Max : 97 

[26  1 17 14 31  8  7 13 45 17] 

[17 21 41 34 42 18 19 13 38 40] 



pandas

In [7]:
def get_df_from_csv(ticker):
    try:
        df = pd.read_csv(PATH + ticker + '.csv', index_col='Date', 
                         parse_dates=True)
    except FileNotFoundError:
        pass
    else:
        return df

In [8]:
msft_df = get_df_from_csv("MSFT")
msft_df

In [9]:
def get_df_from_excel(file):
    try:
        df = pd.read_excel(file)
    except FileNotFoundError:
        pass
        print("File Doesn't Exist")
    else:
        return df

In [10]:
file = PATH + "prev_datasets/Wilshire-5000-Stocks.xlsx"
w_stocks = get_df_from_excel(file)
w_stocks

Ticker                        Company
0         A                       Agilent 
1        AA                         Alcoa 
2       AAL             American Airlines 
3      AAME             Atlantic American 
4       AAN                       Aaron's 
...     ...                            ...
3476   ZUMZ                   Zumiez, Inc.
3477    ZUO                    Zuora, Inc.
3478   ZYNE  Zynerba Pharmaceuticals, Inc.
3479   ZYXI                    Zynex, Inc.
3480   ZNGA                    Zynga, Inc.

[3481 rows x 2 columns]

In [11]:
g_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_current_United_States_governors")
g_data

[                                                    0
 0             This article is part of a series on the
 1              State governments of the United States
 2            State constitution Comparison Statehouse
 3                                           Executive
 4   State executives Governor (List) Other common ...
 5                                         Legislative
 6   State representatives (Alabama to Missouri, Mo...
 7                                           Judiciary
 8                     State supreme court State court
 9                Politics portal United States portal
 10  .mw-parser-output .navbar{display:inline;font-...,
    United States governors  Republican (26)  Democratic (24)        \
                                                        State Image   
 0                                             Alabama          NaN   
 1                                              Alaska          NaN   
 2                                             Arizona 

In [12]:
g_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_current_United_States_governors")[1]
g_data

United States governors  Republican (26)  Democratic (24)        \
                                                       State Image   
0                                             Alabama          NaN   
1                                              Alaska          NaN   
2                                             Arizona          NaN   
3                                            Arkansas          NaN   
4                                          California          NaN   
5                                            Colorado          NaN   
6                                         Connecticut          NaN   
7                                            Delaware          NaN   
8                                             Florida          NaN   
9                                             Georgia          NaN   
10                                             Hawaii          NaN   
11                                              Idaho          NaN   
12                                           Illinois          NaN   
13                                            Indiana          NaN   
14                                               Iowa          NaN   
15                                             Kansas          NaN   
16                                           Kentucky          NaN   
17                                          Louisiana          NaN   
18                                              Maine          NaN   
19                                           Maryland          NaN   
20                                      Massachusetts          NaN   
21                                           Michigan          NaN   
22                                          Minnesota          NaN   
23                                        Mississippi          NaN   
24                                           Missouri          NaN   
25                                            Montana          NaN   
26                                           Nebraska          NaN   
27                                             Nevada          NaN   
28                                      New Hampshire          NaN   
29                                         New Jersey          NaN   
30                                         New Mexico          NaN   
31                                           New York          NaN   
32                                     North Carolina          NaN   
33                                       North Dakota          NaN   
34                                               Ohio          NaN   
35                                           Oklahoma          NaN   
36                                             Oregon          NaN   
37                                       Pennsylvania          NaN   
38                                       Rhode Island          NaN   
39                                     South Carolina          NaN   
40                                       South Dakota          NaN   
41                                          Tennessee          NaN   
42                                              Texas          NaN   
43                                               Utah          NaN   
44                                            Vermont          NaN   
45                                           Virginia          NaN   
46                                         Washington          NaN   
47                                      West Virginia          NaN   
48                                          Wisconsin          NaN   
49                                            Wyoming          NaN   

                                                                     \
                  Governor Party                  Party.1      Born   
0                 Kay Ivey   NaN               Republican  (age 78)   
1            Mike Dunleavy   NaN               Republican  (age 61)   
2              Katie Hobbs   NaN               Democratic  (age 53)   
3   Sar

In [13]:
d_data = pd.read_html("https://en.wikipedia.org/wiki/Demographics_of_the_United_States", 
                      match="Average population")[0]
d_data

Unnamed: 0  Average population[76][30][31]  Live births[77]  \
0                       1935                       127250000          2377000   
1                       1936                       128053000          2355000   
2                       1937                       128825000          2413000   
3                       1938                       129825000          2496000   
4                       1939                       130880000          2466000   
..                       ...                             ...              ...   
82              2017[80][81]                       325122128          3855500   
83              2018[82][83]                       326838199          3791712   
84                      2019                       328329953          3747540   
85              2020[84][85]                       331501080          3613647   
86  2021[86][87][88][89][90]                       331893745          3664292   

     Deaths  Natural change  Crude birth rate (per 1,000)  \
0   1392752          984248                          18.7   
1   1479228          875772                          18.4   
2   1450427          962573                          18.7   
3   1381391         1114609                          19.2   
4   1387897         1078103                          18.8   
..      ...             ...                           ...   
82  2813503         1041997                          11.8   
83  2839205          952507                          11.6   
84  2854858          892682                          11.4   
85  3383729          229918                          10.9   
86  3464231          200061                          11.0   

    Crude death rate (per 1,000)[78]  Natural change (per 1,000)  \
0                               10.9                         7.7   
1                               11.5                         6.8   
2                               11.2                         7.5   
3                               10.6                         8.6   
4                               10.6                         8.2   
..                               ...                         ...   
82                               8.7                         3.1   
83                               8.7                         2.9   
84                               8.7                         2.7   
85                              10.2                         0.7   
86                              10.5                         0.5   

    Total fertility rate[fn 1][79]  
0                            2.190  
1                            2.150  
2                            2.170  
3                            2.220  
4                            2.170  
..                             ...  
82                           1.765  
83                           1.729  
84                           1.706  
85                           1.641  
86                           1.664  

[87 rows x 9 columns]

In [14]:
d_data.columns = [x.replace(' ', '_') for x in d_data.columns]
d_data

Unnamed:_0  Average_population[76][30][31]  Live_births[77]  \
0                       1935                       127250000          2377000   
1                       1936                       128053000          2355000   
2                       1937                       128825000          2413000   
3                       1938                       129825000          2496000   
4                       1939                       130880000          2466000   
..                       ...                             ...              ...   
82              2017[80][81]                       325122128          3855500   
83              2018[82][83]                       326838199          3791712   
84                      2019                       328329953          3747540   
85              2020[84][85]                       331501080          3613647   
86  2021[86][87][88][89][90]                       331893745          3664292   

     Deaths  Natural_change  Crude_birth_rate_(per_1,000)  \
0   1392752          984248                          18.7   
1   1479228          875772                          18.4   
2   1450427          962573                          18.7   
3   1381391         1114609                          19.2   
4   1387897         1078103                          18.8   
..      ...             ...                           ...   
82  2813503         1041997                          11.8   
83  2839205          952507                          11.6   
84  2854858          892682                          11.4   
85  3383729          229918                          10.9   
86  3464231          200061                          11.0   

    Crude_death_rate_(per_1,000)[78]  Natural_change_(per_1,000)  \
0                               10.9                         7.7   
1                               11.5                         6.8   
2                               11.2                         7.5   
3                               10.6                         8.6   
4                               10.6                         8.2   
..                               ...                         ...   
82                               8.7                         3.1   
83                               8.7                         2.9   
84                               8.7                         2.7   
85                              10.2                         0.7   
86                              10.5                         0.5   

    Total_fertility_rate[fn_1][79]  
0                            2.190  
1                            2.150  
2                            2.170  
3                            2.220  
4                            2.170  
..                             ...  
82                           1.765  
83                           1.729  
84                           1.706  
85                           1.641  
86                           1.664  

[87 rows x 9 columns]

In [15]:
d_data.columns = d_data.columns.str.replace(r"\(.*\)","")
d_data.columns = d_data.columns.str.replace(r"\[.*\]","")
d_data

Unnamed:_0  Average_population  Live_births   Deaths  \
0                       1935           127250000      2377000  1392752   
1                       1936           128053000      2355000  1479228   
2                       1937           128825000      2413000  1450427   
3                       1938           129825000      2496000  1381391   
4                       1939           130880000      2466000  1387897   
..                       ...                 ...          ...      ...   
82              2017[80][81]           325122128      3855500  2813503   
83              2018[82][83]           326838199      3791712  2839205   
84                      2019           328329953      3747540  2854858   
85              2020[84][85]           331501080      3613647  3383729   
86  2021[86][87][88][89][90]           331893745      3664292  3464231   

    Natural_change  Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
0           984248               18.7               10.9              7.7   
1           875772               18.4               11.5              6.8   
2           962573               18.7               11.2              7.5   
3          1114609               19.2               10.6              8.6   
4          1078103               18.8               10.6              8.2   
..             ...                ...                ...              ...   
82         1041997               11.8                8.7              3.1   
83          952507               11.6                8.7              2.9   
84          892682               11.4                8.7              2.7   
85          229918               10.9               10.2              0.7   
86          200061               11.0               10.5              0.5   

    Total_fertility_rate  
0                  2.190  
1                  2.150  
2                  2.170  
3                  2.220  
4                  2.170  
..                   ...  
82                 1.765  
83                 1.729  
84                 1.706  
85                 1.641  
86                 1.664  

[87 rows x 9 columns]

In [16]:
d_data = d_data.rename(columns={'Unnamed:_0': 'Year'})
d_data

Year  Average_population  Live_births   Deaths  \
0                       1935           127250000      2377000  1392752   
1                       1936           128053000      2355000  1479228   
2                       1937           128825000      2413000  1450427   
3                       1938           129825000      2496000  1381391   
4                       1939           130880000      2466000  1387897   
..                       ...                 ...          ...      ...   
82              2017[80][81]           325122128      3855500  2813503   
83              2018[82][83]           326838199      3791712  2839205   
84                      2019           328329953      3747540  2854858   
85              2020[84][85]           331501080      3613647  3383729   
86  2021[86][87][88][89][90]           331893745      3664292  3464231   

    Natural_change  Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
0           984248               18.7               10.9              7.7   
1           875772               18.4               11.5              6.8   
2           962573               18.7               11.2              7.5   
3          1114609               19.2               10.6              8.6   
4          1078103               18.8               10.6              8.2   
..             ...                ...                ...              ...   
82         1041997               11.8                8.7              3.1   
83          952507               11.6                8.7              2.9   
84          892682               11.4                8.7              2.7   
85          229918               10.9               10.2              0.7   
86          200061               11.0               10.5              0.5   

    Total_fertility_rate  
0                  2.190  
1                  2.150  
2                  2.170  
3                  2.220  
4                  2.170  
..                   ...  
82                 1.765  
83                 1.729  
84                 1.706  
85                 1.641  
86                 1.664  

[87 rows x 9 columns]

In [17]:
d_data.Year = d_data.Year.str.replace(r"\[.*\]","")
d_data

Year  Average_population  Live_births   Deaths  Natural_change  \
0   1935           127250000      2377000  1392752          984248   
1   1936           128053000      2355000  1479228          875772   
2   1937           128825000      2413000  1450427          962573   
3   1938           129825000      2496000  1381391         1114609   
4   1939           130880000      2466000  1387897         1078103   
..   ...                 ...          ...      ...             ...   
82  2017           325122128      3855500  2813503         1041997   
83  2018           326838199      3791712  2839205          952507   
84  2019           328329953      3747540  2854858          892682   
85  2020           331501080      3613647  3383729          229918   
86  2021           331893745      3664292  3464231          200061   

    Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
0                18.7               10.9              7.7   
1                18.4               11.5              6.8   
2                18.7               11.2              7.5   
3                19.2               10.6              8.6   
4                18.8               10.6              8.2   
..                ...                ...              ...   
82               11.8                8.7              3.1   
83               11.6                8.7              2.9   
84               11.4                8.7              2.7   
85               10.9               10.2              0.7   
86               11.0               10.5              0.5   

    Total_fertility_rate  
0                  2.190  
1                  2.150  
2                  2.170  
3                  2.220  
4                  2.170  
..                   ...  
82                 1.765  
83                 1.729  
84                 1.706  
85                 1.641  
86                 1.664  

[87 rows x 9 columns]

In [18]:
d_data.Live_births

0     2377000
1     2355000
2     2413000
3     2496000
4     2466000
       ...   
82    3855500
83    3791712
84    3747540
85    3613647
86    3664292
Name: Live_births, Length: 87, dtype: int64

In [19]:
d_data['Deaths']

0     1392752
1     1479228
2     1450427
3     1381391
4     1387897
       ...   
82    2813503
83    2839205
84    2854858
85    3383729
86    3464231
Name: Deaths, Length: 87, dtype: int64

In [20]:
d_data.set_index('Year', inplace=True)
d_data

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1935           127250000      2377000  1392752          984248   
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
Year                                                          
1935               18.7               10.9              7.7   
1936               18.4               11.5              6.8   
1937               18.7               11.2              7.5   
1938               19.2               10.6              8.6   
1939               18.8               10.6              8.2   
...                 ...                ...              ...   
2017               11.8                8.7              3.1   
2018               11.6                8.7              2.9   
2019               11.4                8.7              2.7   
2020               10.9               10.2              0.7   
2021               11.0               10.5              0.5   

      Total_fertility_rate  
Year                        
1935                 2.190  
1936                 2.150  
1937                 2.170  
1938                 2.220  
1939                 2.170  
...                    ...  
2017                 1.765  
2018                 1.729  
2019                 1.706  
2020                 1.641  
2021                 1.664  

[87 rows x 8 columns]

In [21]:
d_data[["Live_births", "Deaths"]]

Live_births   Deaths
Year                      
1935      2377000  1392752
1936      2355000  1479228
1937      2413000  1450427
1938      2496000  1381391
1939      2466000  1387897
...           ...      ...
2017      3855500  2813503
2018      3791712  2839205
2019      3747540  2854858
2020      3613647  3383729
2021      3664292  3464231

[87 rows x 2 columns]

In [22]:
d_data.loc['2020']

Average_population      3.315011e+08
Live_births             3.613647e+06
Deaths                  3.383729e+06
Natural_change          2.299180e+05
Crude_birth_rate_       1.090000e+01
Crude_death_rate_       1.020000e+01
Natural_change_         7.000000e-01
Total_fertility_rate    1.641000e+00
Name: 2020, dtype: float64

In [23]:
d_data.iloc[85]

Average_population      3.315011e+08
Live_births             3.613647e+06
Deaths                  3.383729e+06
Natural_change          2.299180e+05
Crude_birth_rate_       1.090000e+01
Crude_death_rate_       1.020000e+01
Natural_change_         7.000000e-01
Total_fertility_rate    1.641000e+00
Name: 2020, dtype: float64

In [24]:
d_data['Pop_Growth'] = d_data["Live_births"] - d_data["Deaths"]
d_data

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1935           127250000      2377000  1392752          984248   
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
Year                                                          
1935               18.7               10.9              7.7   
1936               18.4               11.5              6.8   
1937               18.7               11.2              7.5   
1938               19.2               10.6              8.6   
1939               18.8               10.6              8.2   
...                 ...                ...              ...   
2017               11.8                8.7              3.1   
2018               11.6                8.7              2.9   
2019               11.4                8.7              2.7   
2020               10.9               10.2              0.7   
2021               11.0               10.5              0.5   

      Total_fertility_rate  Pop_Growth  
Year                                    
1935                 2.190      984248  
1936                 2.150      875772  
1937                 2.170      962573  
1938                 2.220     1114609  
1939                 2.170     1078103  
...                    ...         ...  
2017                 1.765     1041997  
2018                 1.729      952507  
2019                 1.706      892682  
2020                 1.641      229918  
2021                 1.664      200061  

[87 rows x 9 columns]

In [25]:
d_data.drop('Pop_Growth', axis=1, inplace=True)
d_data

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1935           127250000      2377000  1392752          984248   
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
Year                                                          
1935               18.7               10.9              7.7   
1936               18.4               11.5              6.8   
1937               18.7               11.2              7.5   
1938               19.2               10.6              8.6   
1939               18.8               10.6              8.2   
...                 ...                ...              ...   
2017               11.8                8.7              3.1   
2018               11.6                8.7              2.9   
2019               11.4                8.7              2.7   
2020               10.9               10.2              0.7   
2021               11.0               10.5              0.5   

      Total_fertility_rate  
Year                        
1935                 2.190  
1936                 2.150  
1937                 2.170  
1938                 2.220  
1939                 2.170  
...                    ...  
2017                 1.765  
2018                 1.729  
2019                 1.706  
2020                 1.641  
2021                 1.664  

[87 rows x 8 columns]

In [26]:
d_data.drop('1935', axis=0, inplace=True)
d_data

Average_population  Live_births   Deaths  Natural_change  \
Year                                                             
1936           128053000      2355000  1479228          875772   
1937           128825000      2413000  1450427          962573   
1938           129825000      2496000  1381391         1114609   
1939           130880000      2466000  1387897         1078103   
1940           131930000      2559000  1417269         1142000   
...                  ...          ...      ...             ...   
2017           325122128      3855500  2813503         1041997   
2018           326838199      3791712  2839205          952507   
2019           328329953      3747540  2854858          892682   
2020           331501080      3613647  3383729          229918   
2021           331893745      3664292  3464231          200061   

      Crude_birth_rate_  Crude_death_rate_  Natural_change_  \
Year                                                          
1936               18.4               11.5              6.8   
1937               18.7               11.2              7.5   
1938               19.2               10.6              8.6   
1939               18.8               10.6              8.2   
1940               19.4               10.8              8.7   
...                 ...                ...              ...   
2017               11.8                8.7              3.1   
2018               11.6                8.7              2.9   
2019               11.4                8.7              2.7   
2020               10.9               10.2              0.7   
2021               11.0               10.5              0.5   

      Total_fertility_rate  
Year                        
1936                 2.150  
1937                 2.170  
1938                 2.220  
1939                 2.170  
1940                 2.301  
...                    ...  
2017                 1.765  
2018                 1.729  
2019                 1.706  
2020                 1.641  
2021                 1.664  

[86 rows x 8 columns]

In [27]:
c_data = pd.read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)")[2]
c_data

Country/Territory UN Region IMF[1][13]            World Bank[14]  \
    Country/Territory UN Region   Estimate       Year       Estimate   
0               World         —  101560901       2022       96513077   
1       United States  Americas   25035164       2022       22996100   
2               China      Asia   18321197  [n 1]2022       17734063   
3               Japan      Asia    4300621       2022        4937422   
4             Germany    Europe    4031149       2022        4223116   
..                ...       ...        ...        ...            ...   
212             Palau   Oceania        226       2022            218   
213          Kiribati   Oceania        207       2022            207   
214             Nauru   Oceania        134       2022            133   
215        Montserrat  Americas          —          —              —   
216            Tuvalu   Oceania         64       2022             63   

               United Nations[15]             
          Year           Estimate       Year  
0         2021           85328323       2020  
1         2021           20893746       2020  
2    [n 3]2021           14722801  [n 1]2020  
3         2021            5057759       2020  
4         2021            3846414       2020  
..         ...                ...        ...  
212       2021                264       2020  
213       2021                181       2020  
214       2021                135       2020  
215          —                 68       2020  
216       2021                 55       2020  

[217 rows x 8 columns]

In [28]:
for col in c_data.columns:
    print(col)

('Country/Territory', 'Country/Territory')
('UN Region', 'UN Region')
('IMF[1][13]', 'Estimate')
('IMF[1][13]', 'Year')
('World Bank[14]', 'Estimate')
('World Bank[14]', 'Year')
('United Nations[15]', 'Estimate')
('United Nations[15]', 'Year')


In [29]:
c_data.columns = c_data.columns.droplevel()
c_data

Country/Territory UN Region   Estimate       Year  Estimate       Year  \
0               World         —  101560901       2022  96513077       2021   
1       United States  Americas   25035164       2022  22996100       2021   
2               China      Asia   18321197  [n 1]2022  17734063  [n 3]2021   
3               Japan      Asia    4300621       2022   4937422       2021   
4             Germany    Europe    4031149       2022   4223116       2021   
..                ...       ...        ...        ...       ...        ...   
212             Palau   Oceania        226       2022       218       2021   
213          Kiribati   Oceania        207       2022       207       2021   
214             Nauru   Oceania        134       2022       133       2021   
215        Montserrat  Americas          —          —         —          —   
216            Tuvalu   Oceania         64       2022        63       2021   

     Estimate       Year  
0    85328323       2020  
1    20893746       2020  
2    14722801  [n 1]2020  
3     5057759       2020  
4     3846414       2020  
..        ...        ...  
212       264       2020  
213       181       2020  
214       135       2020  
215        68       2020  
216        55       2020  

[217 rows x 8 columns]

In [30]:
c_data = c_data.loc[:,~c_data.columns.duplicated()]
c_data

Country/Territory UN Region   Estimate       Year
0               World         —  101560901       2022
1       United States  Americas   25035164       2022
2               China      Asia   18321197  [n 1]2022
3               Japan      Asia    4300621       2022
4             Germany    Europe    4031149       2022
..                ...       ...        ...        ...
212             Palau   Oceania        226       2022
213          Kiribati   Oceania        207       2022
214             Nauru   Oceania        134       2022
215        Montserrat  Americas          —          —
216            Tuvalu   Oceania         64       2022

[217 rows x 4 columns]

In [31]:
c_data = c_data[c_data['Estimate'].notna()]
c_data

Country/Territory UN Region   Estimate       Year
0               World         —  101560901       2022
1       United States  Americas   25035164       2022
2               China      Asia   18321197  [n 1]2022
3               Japan      Asia    4300621       2022
4             Germany    Europe    4031149       2022
..                ...       ...        ...        ...
212             Palau   Oceania        226       2022
213          Kiribati   Oceania        207       2022
214             Nauru   Oceania        134       2022
215        Montserrat  Americas          —          —
216            Tuvalu   Oceania         64       2022

[217 rows x 4 columns]

In [32]:
c_data.Year = c_data.Year.str.replace(r"\[.*\]","")
c_data

Country/Territory UN Region   Estimate  Year
0               World         —  101560901  2022
1       United States  Americas   25035164  2022
2               China      Asia   18321197  2022
3               Japan      Asia    4300621  2022
4             Germany    Europe    4031149  2022
..                ...       ...        ...   ...
212             Palau   Oceania        226  2022
213          Kiribati   Oceania        207  2022
214             Nauru   Oceania        134  2022
215        Montserrat  Americas          —     —
216            Tuvalu   Oceania         64  2022

[217 rows x 4 columns]

In [33]:
c_data.rename(columns={"Country/Territory": "Country", "Estimate": "GDP"}, inplace=True)
c_data

Country UN Region        GDP  Year
0            World         —  101560901  2022
1    United States  Americas   25035164  2022
2            China      Asia   18321197  2022
3            Japan      Asia    4300621  2022
4          Germany    Europe    4031149  2022
..             ...       ...        ...   ...
212          Palau   Oceania        226  2022
213       Kiribati   Oceania        207  2022
214          Nauru   Oceania        134  2022
215     Montserrat  Americas          —     —
216         Tuvalu   Oceania         64  2022

[217 rows x 4 columns]

In [34]:
c_data.Country = c_data.Country.str.replace("*","")
c_data

Country UN Region        GDP  Year
0            World         —  101560901  2022
1    United States  Americas   25035164  2022
2            China      Asia   18321197  2022
3            Japan      Asia    4300621  2022
4          Germany    Europe    4031149  2022
..             ...       ...        ...   ...
212          Palau   Oceania        226  2022
213       Kiribati   Oceania        207  2022
214          Nauru   Oceania        134  2022
215     Montserrat  Americas          —     —
216         Tuvalu   Oceania         64  2022

[217 rows x 4 columns]

In [35]:
c_data.groupby("UN Region").mean()

Empty DataFrame
Columns: []
Index: [Africa, Americas, Asia, Europe, Oceania, —]

In [36]:
c_data.groupby("UN Region").median()

Empty DataFrame
Columns: []
Index: [Africa, Americas, Asia, Europe, Oceania, —]

In [37]:
dict1 = {'Store': [1,2,1,2], 'Flavor': ['Choc', 'Van', 'Straw', 'Choc'], 
         'Sales': [26, 12, 18, 22]}

ic_data = pd.DataFrame(dict1)


by_store = ic_data.groupby('Store')
by_store.mean()

Sales
Store       
1       22.0
2       17.0

In [38]:
by_store.sum().loc[1]

Sales    44
Name: 1, dtype: int64

In [39]:
by_store.describe()

Sales                                              
      count  mean       std   min   25%   50%   75%   max
Store                                                    
1       2.0  22.0  5.656854  18.0  20.0  22.0  24.0  26.0
2       2.0  17.0  7.071068  12.0  14.5  17.0  19.5  22.0

plotly

In [40]:
import cufflinks as cf
import plotly.express as px
import plotly.graph_objects as go

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

cf.go_offline()

In [44]:
df_stocks = px.data.stocks()

px.line(df_stocks, x='date', y=['GOOG','AAPL'], labels={'x':'Date', 
                                                        'y':'Value of Dollar'},
                                                        title='Apple Vs. Google')